# IMPORTANT: This application does not use a database.
# It uses Redis exclusively for caching weather data.

# Since ActiveRecord is not loaded (commented out in application.rb),
# we only need an empty configuration file to satisfy Rails conventions.
# No database will be created or used in any environment.

development:
  adapter: none

test:
  adapter: none

# Production also doesn't use a database
production:
  <<: *default
  database: non_existent_db
