# IMPORTANT: This application does not use a database.
# It uses Redis exclusively for caching weather data.
# This is a null configuration to prevent database creation in CI environments.

# Define an adapter that won't attempt to connect to any database
default: &default
  adapter: nulldb
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: non_existent_db

# Used for running tests - no actual database is created
test:
  <<: *default
  database: non_existent_db

# Production also doesn't use a database
production:
  <<: *default
  database: non_existent_db
